### ISSUE TITLE
Publish Facial Age Estimator model code

### ISSUE THREAD

**Issue by ptitzler** [CODAIT/max-tfjs-models#3]
https://github.com/IBM/fae-tfjs currently includes the fae TFJS model code. We need to extract and repackage it.

**Comment by ptitzler** [comment]
@vabarbosa if you could advise Daniel ...

**Comment by ptitzler** [comment]
https://github.ibm.com/CODAIT/Model-Asset-Exchange/issues/147

**Comment by vabarbosa** [comment]
work has been completed and age estimator model published

- https://www.npmjs.com/package/@codait/max-facial-age-estimator

related PR #4  

@djalova thanks!
